//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDefinitivoComEntityFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCDefinitivoComEntityFrameworEntities3 : DbContext
    {
        public MVCDefinitivoComEntityFrameworEntities3()
            : base("name=MVCDefinitivoComEntityFrameworEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_autor2> tb_autor2 { get; set; }
        public virtual DbSet<tb_livro> tb_livro { get; set; }
    }
}
