//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDefinitivoComEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_autor2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_autor2()
        {
            this.tb_livro = new HashSet<tb_livro>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string QtdLivrosEscritos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_livro> tb_livro { get; set; }
    }
}
