//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDefinitivoComEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_livro
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Categoria { get; set; }
        public Nullable<System.DateTime> DataLancamento { get; set; }
        public Nullable<int> AutorLivro { get; set; }
    
        public virtual tb_autor2 tb_autor2 { get; set; }
    }
}
